version: 2

project_name: db-snap

before:
  hooks:
    - go mod tidy

builds:
  - id: db-snap
    main: ./cmd/db-snap
    binary: db-snap
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: default
    ids:
      - db-snap
    formats:
      - tar.gz
    name_template: "db-snap_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files: []

checksum:
  name_template: checksums.txt

changelog:
  disable: true
